# Configuration file for Calamares
# Syntax is YAML 1.2
---

# "local" is LIBDIR/calamares/modules with settings in SHARE/calamares/modules
modules-search: [ local, /usr/lib/calamares/modules ]

# If this is set to true, Calamares refers to itself as a "setup program"
# rather than an "installer". Defaults to the value of dont-chroot, but
# Calamares will complain if this is not explicitly set.
oem-setup: false

# If this is set to true, the "Cancel" button will be disabled entirely.
# The button is also hidden from view.
disable-cancel: false

# If this is set to true, the "Cancel" button will be disabled once
# you start the 'Installation', meaning there won't be a way to cancel
# the installation until it has finished or installation has failed.
disable-cancel-during-exec: false

# If this is set to true, then once the end of the sequence has
# been reached, the quit (done) button is clicked automatically
# and Calamares will close.
quit-at-end: false

sequence:
# Phase 1 - prepare.
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - packagechooser
  - summary

# Phase 2 - install.
- exec:
  - partition
  - mount
  - unpackfs
  - luksbootkeyfile
  - dpkg-unsafe-io
  - sources-media
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - bootloader-config
  - grubcfg
  - bootloader
  - packages
  - contextualprocess
  - shellprocess
  - initramfscfg
  - initramfs
  - dpkg-unsafe-io-undo
  - sources-media-unmount
  - sources-final
  - umount

# Phase 3 - postinstall.
- show:
  - finished

# Branding component (Darkian Linux, in /etc/calamares/branding/darkian).
branding: darkian

# If this is set to true, Calamares will show an "Are you sure?" prompt right
# before each execution phase, i.e. at points of no return.
prompt-install: false

# If this is set to true, Calamares will execute all target environment
# commands in the current environment, without chroot.
dont-chroot: false
